#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

IOS_PROFILE_CACHE=~/.soomla/cache/ios-profile
mkdir -p $IOS_PROFILE_CACHE

mkdir -p libs

FB_SDK_NAME=facebook-4.10.1.zip
if [ ! -d libs/FBSDKShareKit.framework ];
then
    if [ ! -f $IOS_PROFILE_CACHE/$FB_SDK_NAME ];
    then
        echo "Downloading Facebook iOS SDK..."
        curl -Lo $IOS_PROFILE_CACHE/$FB_SDK_NAME.tmp https://origincache.facebook.com/developers/resources/?id=FacebookSDKs-iOS-20160316.zip
        mv $IOS_PROFILE_CACHE/$FB_SDK_NAME.tmp $IOS_PROFILE_CACHE/$FB_SDK_NAME
    fi
	mkdir -p fb-sources
	unzip $IOS_PROFILE_CACHE/$FB_SDK_NAME -d fb-sources
	cp -r fb-sources/*.framework libs/
	cp -r fb-sources/*.bundle libs/
	rm -rf fb-sources
fi